//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventario
    {
        public int IdInventario { get; set; }
        public int Existencias { get; set; }
        public int Minimo { get; set; }
        public int IdProducto { get; set; }
        public int IdSeccionBodega { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual SeccionBodega SeccionBodega { get; set; }
    }
}
